import Foundation

/// Per-platform listing draft for an item. One item has up to three listings
/// (Vinted, Depop, eBay). Mirrors the `listings` table in
/// `docs/data-model.md` and the listing-reformat prompt (Prompt 2) output.
///
/// The status field tracks the cross-listing lifecycle (ADR-007):
/// - `.draft` — generated by AI, not yet sent
/// - `.copied` — user has copied to clipboard (legacy v1 flow)
/// - `.posted` — automated cross-listing posted it (eBay native API, or
///   Vinted/Depop via WKWebView per ADR-007 Phase B/C)
/// - `.sold` — confirmed sold via email-forward detection or manual mark
public struct Listing: Codable, Identifiable, Hashable, Sendable {
    public let id: UUID
    public let itemId: UUID
    public let platform: Platform
    public var title: String?
    public var description: String?
    public var categoryId: String?
    public var tags: [String]
    public var price: Decimal?
    public var status: ListingStatus
    public var postedAt: Date?
    public var postedUrl: URL?

    public init(
        id: UUID,
        itemId: UUID,
        platform: Platform,
        title: String? = nil,
        description: String? = nil,
        categoryId: String? = nil,
        tags: [String] = [],
        price: Decimal? = nil,
        status: ListingStatus = .draft,
        postedAt: Date? = nil,
        postedUrl: URL? = nil
    ) {
        self.id = id
        self.itemId = itemId
        self.platform = platform
        self.title = title
        self.description = description
        self.categoryId = categoryId
        self.tags = tags
        self.price = price
        self.status = status
        self.postedAt = postedAt
        self.postedUrl = postedUrl
    }
}

public enum ListingStatus: String, Codable, CaseIterable, Sendable {
    case draft
    case copied
    case posted
    case sold

    public var displayName: String {
        switch self {
        case .draft: return "Draft"
        case .copied: return "Copied"
        case .posted: return "Posted"
        case .sold: return "Sold"
        }
    }
}
